const restaurants = [
  { country: "Brazil",
    retaurantName: "Chama Gaúcha Brazilian Steakhouse",
    streetNumber: 5865,
    streetName: "Westheimer Road",
  },
  { country: "Ethiopia",
    retaurantName: "Lucy Ethiopian Restaurant & Lounge",
    streetNumber: 6800,
    streetName: "Southwest Freeway",
  },
  { country: "Germany",
    retaurantName: "Rudi Lechner’s German Restaurant",
    streetNumber: 2503,
    streetName: "South Gessner Road",
  },
  { country: "Honduras",
    retaurantName: "Mi Bella Honduras Restaurant",
    streetNumber: 1806,
    streetName: "Wirt Road",
  },
  { country: "India",
    retaurantName: "Surya India",
    streetNumber: 700,
    streetName: "Durham Drive",
  },
  { country: "Thailand",
    retaurantName: "Thai Gourmet",
    streetNumber: 6324,
    streetName: "Richmond Avenue",
  },
];

module.exports = restaurants;
