const restaurants = [
  {
    key: 0,
    country: "Brazil",
    retaurantName: "Chama Gaúcha Brazilian Steakhouse",
    streetNumber: 5865,
    streetName: "Westheimer Road",
    lat: 29.73,
    lng: -95.48,
  },
  {
    key: 1,
    country: "Ethiopia",
    retaurantName: "Lucy Ethiopian Restaurant & Lounge",
    streetNumber: 6800,
    streetName: "Southwest Freeway",
    lat: 29.71,
    lng: -95.50,
  },
  {
    key: 2,
    country: "Germany",
    retaurantName: "Rudi Lechner’s German Restaurant",
    streetNumber: 2503,
    streetName: "South Gessner Road",
    lat: 29.74,
    lng: -95.53,
  },
  {
    key: 3,
    country: "Honduras",
    retaurantName: "Mi Bella Honduras Restaurant",
    streetNumber: 1806,
    streetName: "Wirt Road",
    lat: 29.80,
    lng: -95.48,
  },
  {
    key: 4,
    country: "India",
    retaurantName: "Surya India",
    streetNumber: 700,
    streetName: "Durham Drive",
    lat: 29.76,
    lng: -95.41,
  },
  {
    key: 5,
    country: "Italy",
    retaurantName: "Bellissimo Ristorante",
    streetNumber: 1848,
    streetName: "Airline Drive",
    lat: 29.80,
    lng: -95.38,
  },
  {
    key: 6,
    country: "Thailand",
    retaurantName: "Thai Gourmet",
    streetNumber: 6324,
    streetName: "Richmond Avenue",
    lat: 29.73,
    lng: -95.49,
  },
];

module.exports = restaurants;
